/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as ProtectedCareerRouteImport } from './routes/_protected/_career'
import { Route as ProtectedAppRouteImport } from './routes/_protected/app'
import { Route as ProtectedProfileRouteImport } from './routes/_protected/profile'
import { Route as ProtectedCareerIndexRouteImport } from './routes/_protected/_career/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedCareerCareerStepsStepIdEditRouteImport } from './routes/_protected/_career/career-steps/$stepId/edit'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedCareerRoute = ProtectedCareerRouteImport.update({
  id: '/_career',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAppRoute = ProtectedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCareerIndexRoute = ProtectedCareerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedCareerRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedCareerCareerStepsStepIdEditRoute =
  ProtectedCareerCareerStepsStepIdEditRouteImport.update({
    id: '/career-steps/$stepId/edit',
    path: '/career-steps/$stepId/edit',
    getParentRoute: () => ProtectedCareerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedCareerIndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/app': typeof ProtectedAppRoute
  '/profile': typeof ProtectedProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/career-steps/$stepId/edit': typeof ProtectedCareerCareerStepsStepIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedCareerIndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/app': typeof ProtectedAppRoute
  '/profile': typeof ProtectedProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/career-steps/$stepId/edit': typeof ProtectedCareerCareerStepsStepIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_protected/_career': typeof ProtectedCareerRouteWithChildren
  '/_protected/app': typeof ProtectedAppRoute
  '/_protected/profile': typeof ProtectedProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/_career/': typeof ProtectedCareerIndexRoute
  '/_protected/_career/career-steps/$stepId/edit': typeof ProtectedCareerCareerStepsStepIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/app'
    | '/profile'
    | '/api/auth/$'
    | '/career-steps/$stepId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/app'
    | '/profile'
    | '/api/auth/$'
    | '/career-steps/$stepId/edit'
  id:
    | '__root__'
    | '/_protected'
    | '/sign-in'
    | '/sign-up'
    | '/_protected/_career'
    | '/_protected/app'
    | '/_protected/profile'
    | '/api/auth/$'
    | '/_protected/_career/'
    | '/_protected/_career/career-steps/$stepId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/_career': {
      id: '/_protected/_career'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedCareerRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/app': {
      id: '/_protected/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof ProtectedAppRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_career/': {
      id: '/_protected/_career/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedCareerIndexRouteImport
      parentRoute: typeof ProtectedCareerRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/_career/career-steps/$stepId/edit': {
      id: '/_protected/_career/career-steps/$stepId/edit'
      path: '/career-steps/$stepId/edit'
      fullPath: '/career-steps/$stepId/edit'
      preLoaderRoute: typeof ProtectedCareerCareerStepsStepIdEditRouteImport
      parentRoute: typeof ProtectedCareerRoute
    }
  }
}

interface ProtectedCareerRouteChildren {
  ProtectedCareerIndexRoute: typeof ProtectedCareerIndexRoute
  ProtectedCareerCareerStepsStepIdEditRoute: typeof ProtectedCareerCareerStepsStepIdEditRoute
}

const ProtectedCareerRouteChildren: ProtectedCareerRouteChildren = {
  ProtectedCareerIndexRoute: ProtectedCareerIndexRoute,
  ProtectedCareerCareerStepsStepIdEditRoute:
    ProtectedCareerCareerStepsStepIdEditRoute,
}

const ProtectedCareerRouteWithChildren = ProtectedCareerRoute._addFileChildren(
  ProtectedCareerRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedCareerRoute: typeof ProtectedCareerRouteWithChildren
  ProtectedAppRoute: typeof ProtectedAppRoute
  ProtectedProfileRoute: typeof ProtectedProfileRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedCareerRoute: ProtectedCareerRouteWithChildren,
  ProtectedAppRoute: ProtectedAppRoute,
  ProtectedProfileRoute: ProtectedProfileRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
